# Generated by Django 5.1.7 on 2025-03-12 09:07

import user_side.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=user_side.models.default_expiry),
        ),
    ]
